openapi: 3.0.0
info:
  title: AltCloudEvent API
  description: API for handling cloud events with a type discriminator.
  version: 1.0.0

paths:
  /events:
    post:
      summary: Create a new event
      operationId: createEvent
      requestBody:
        content:
          application/json:
            schema:
              type: object
              discriminator:
                propertyName: type
              required:
                - type
              properties:
                type:
                  type: string
                  description: The type of event.
                data:
                  type: object
                  description: Event-specific data.
              oneOf:
                - $ref: '#/components/schemas/org.camaraproject.qod.system-health-event'
                - $ref: '#/components/schemas/org.camaraproject.qod.user-login-event'
      responses:
        '200':
          description: Event successfully created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  message:
                    type: string
                    example: "Event successfully created"
                  eventId:
                    type: string
                    example: "12345"
        '400':
          description: Invalid event data provided.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "error"
                  message:
                    type: string
                    example: "Invalid event data."
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "error"
                  message:
                    type: string
                    example: "An unexpected error occurred."
components:
  schemas:
    org.camaraproject.qod.system-health-event:
      type: object
      properties:
        type:
          type: string
          enum: [org.camaraproject.qod.system-health-event]
        status:
          type: string
          description: The health status of the system.
        timestamp:
          type: string
          format: date-time
          description: The time when the system health event was triggered.

    org.camaraproject.qod.user-login-event:
      type: object
      properties:
        type:
          type: string
          enum: [org.camaraproject.qod.user-login-event]
        username:
          type: string
          description: The username of the user who logged in.
        ipAddress:
          type: string
          description: The IP address from which the user logged in.
        timestamp:
          type: string
          format: date-time
          description: The time of the user login event.
