openapi: 3.0.0
info:
  title: CloudEvent API
  version: 1.0.0
paths:
  /events:
    post:
      summary: "Send a CloudEvent"
      operationId: sendCloudEvent
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CloudEvent"
      responses:
        '200':
          description: Successfully received CloudEvent
components:
  schemas:
    CloudEvent:
      type: object
      properties:
        specversion:
          type: string
          description: The version of the CloudEvent specification.
          example: "1.0"
        type:
          type: string
          description: The type of the event.
          example: "org.camaraproject.qod.user-login-event"
        source:
          type: string
          description: The source of the event.
          example: "https://example.com"
        id:
          type: string
          description: The unique identifier for the event.
          example: "1234-5678-90ab-cdef"
        time:
          type: string
          format: date-time
          description: The time when the event was emitted.
          example: "2025-03-24T12:34:56Z"
        datacontenttype:
          type: string
          description: The content type of the data.
          example: "application/json"
        data:
          type: object
          description: The event data (payload).
          additionalProperties: true
      oneOf:
        - $ref: "#/components/schemas/org.camaraproject.qod.user-login-event"
        - $ref: "#/components/schemas/org.camaraproject.detail-event"
    
    org.camaraproject.qod.user-login-event:
      type: object
      properties:
        eventDetail:
          type: string
          description: "Details specific to the example event."
          example: "Example detail data"
    
    org.camaraproject.detail-event:
      type: object
      properties:
        eventDetail:
          type: string
          description: "Details specific to the other event."
          example: "Other event detail"
